/**
 * NativeAegisBridge — JSI TurboModule Specification
 * 
 * This is the TypeScript interface definition for the C++ JSI
 * TurboModule that bridges zenoh-pico directly into the React
 * Native runtime for sub-10ms telemetry latency.
 * 
 * SCAFFOLD PHASE: This file defines the interface contract.
 * The actual C++ implementation in ios/ and android/ will be
 * built in Phase 2 when native compilation targets are active.
 * 
 * Architecture:
 *   JS Thread ↔ JSI (synchronous) ↔ zenoh-pico C library
 *   No JSON bridge. No async serialization overhead.
 */

import type { TurboModule } from 'react-native';

/**
 * The native module interface. In production, this would be
 * generated by react-native-codegen from the spec.
 */
export interface AegisBridgeSpec extends TurboModule {
  /**
   * Open a Zenoh session to the given endpoint.
   * Returns a session handle (opaque integer).
   */
  openSession(endpoint: string): Promise<number>;

  /**
   * Close an active Zenoh session.
   */
  closeSession(sessionHandle: number): Promise<void>;

  /**
   * Subscribe to a Zenoh key expression.
   * Telemetry data will be delivered via the onTelemetry event.
   */
  subscribe(sessionHandle: number, keyExpr: string): Promise<number>;

  /**
   * Publish a command to a Zenoh key expression.
   * Used for ESTOP and mission commands.
   */
  publish(sessionHandle: number, keyExpr: string, payload: string): Promise<void>;

  /**
   * Get the round-trip latency to the endpoint in microseconds.
   * Critical for verifying ESTOP latency budgets.
   */
  measureLatency(sessionHandle: number): Promise<number>;
}

// Placeholder: In production, this would be:
// export default TurboModuleRegistry.getEnforcing<AegisBridgeSpec>('AegisBridge');
// For scaffold phase, we export a mock implementation.

export const AegisBridgeMock: AegisBridgeSpec = {
  openSession: async (_endpoint: string) => {
    console.log('[AegisBridge/MOCK] openSession');
    return 1;
  },
  closeSession: async (_handle: number) => {
    console.log('[AegisBridge/MOCK] closeSession');
  },
  subscribe: async (_handle: number, keyExpr: string) => {
    console.log(`[AegisBridge/MOCK] subscribe: ${keyExpr}`);
    return 1;
  },
  publish: async (_handle: number, keyExpr: string, _payload: string) => {
    console.log(`[AegisBridge/MOCK] publish: ${keyExpr}`);
  },
  measureLatency: async (_handle: number) => {
    return 500; // 500μs mock latency
  },
} as AegisBridgeSpec;
